language: node_js
node_js:
- 10
- 12
matrix:
  fast_finish: true
notifications:
  email: false
  slack:
    secure: kl3WypWIcpAgX7IOt5/w3cO1KZHClXTqlaTTpTU0mDRmf4HXNUps1+r9G9nDYH9upeYUSh3R5ZTDuKYpjcDpZmCE6WrCiwzdsVh1Wp6Njsl+gDjT3qWMlj+87ONCpWsPZvq/Lh0oniv8txzQ4c+VefhbZE82mqvrn6GfZgkO1MVpwMHr4LCPOuO3sUN3VEjq2Esq4kqa0xOGQBVZLTpCU5aQ5sjmehlBC5ww6RbWLW9C0lSbrOq0bLgLnxfmDV3NgLS/CBctI2rIHEfIE1YeYDxR2pWolgCtJtb/8hIfDR/MFS3/LQjOMlxkqAe228znR5ZKaO2Xje53Wo6CDM24MIIf0rQSZuNQJ4ri2Xh01efwOj4slAwEGfNi3aX5w8h/OL0xq3ptPBOsbL3OZh2lccBOGfBDdbROyxpbOo6eTcyuYILshqJWLq5QqU34I3IQbjU09vHSeW6gbhC6bQYyWnJr2kswt/2f79vDoCJDdkxOjsqcyDus9DGzg3V3finwOJ29mRRcaOPXbFJ2fTLZtTOdFjNxCCjlRDooq/K/tN2aFdy2qWa9JNC1FKu0JRQaNcp3y2EOQbVMK2srYCywXYlboNeenEcUVcVTuj7TpOpbsQNPw9cgtFnXBZeeYLrbGqr6y1Il0y61wwTc78zMJkR5YBAC3xWFvbCHDSVP1i4=
cache:
  directories:
  - "$HOME/.npm"
